# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/indic-clip',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/indic-clip',
                'lib_path': 'indic_clip'},
  'syms': {'indic_clip.core': {'indic_clip.core.foo': ('core.html#foo', 'indic_clip/core.py')}}}
