# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/indic-clip',
                'doc_host': 'https://numb3r33\n'
                            '\n'
                            'requirements = fastai==2.7.12 transformers timm requests beautifulsoup4 imagehash sentencepiece '
                            'gradio.github.io',
                'git_url': 'https://github.com/numb3r33\n'
                           '\n'
                           'requirements = fastai==2.7.12 transformers timm requests beautifulsoup4 imagehash sentencepiece '
                           'gradio/indic-clip',
                'lib_path': 'indic_clip'},
  'syms': { 'indic_clip.core': { 'indic_clip.core.ensure_dir': ('core.html#ensure_dir', 'indic_clip/core.py'),
                                 'indic_clip.core.get_logger': ('core.html#get_logger', 'indic_clip/core.py'),
                                 'indic_clip.core.setup_logging': ('core.html#setup_logging', 'indic_clip/core.py')},
            'indic_clip.data.collection': { 'indic_clip.data.collection.download_kaggle_dataset': ( 'data_collection.html#download_kaggle_dataset',
                                                                                                    'indic_clip/data/collection.py'),
                                            'indic_clip.data.collection.get_sanskrit_data_placeholder': ( 'data_collection.html#get_sanskrit_data_placeholder',
                                                                                                          'indic_clip/data/collection.py'),
                                            'indic_clip.data.collection.get_synthetic_data_placeholder': ( 'data_collection.html#get_synthetic_data_placeholder',
                                                                                                           'indic_clip/data/collection.py'),
                                            'indic_clip.data.collection.load_hindi_captions': ( 'data_collection.html#load_hindi_captions',
                                                                                                'indic_clip/data/collection.py'),
                                            'indic_clip.data.collection.save_formatted_data': ( 'data_collection.html#save_formatted_data',
                                                                                                'indic_clip/data/collection.py'),
                                            'indic_clip.data.collection.unzip_file': ( 'data_collection.html#unzip_file',
                                                                                       'indic_clip/data/collection.py')},
            'indic_clip.data.tokenization': { 'indic_clip.data.tokenization.IndicBERTTokenizer': ( 'data_tokenization.html#indicberttokenizer',
                                                                                                   'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.__init__': ( 'data_tokenization.html#indicberttokenizer.__init__',
                                                                                                            'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer._add_custom_special_tokens': ( 'data_tokenization.html#indicberttokenizer._add_custom_special_tokens',
                                                                                                                              'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.decode': ( 'data_tokenization.html#indicberttokenizer.decode',
                                                                                                          'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.load_tokenizer': ( 'data_tokenization.html#indicberttokenizer.load_tokenizer',
                                                                                                                  'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.pad_token_id': ( 'data_tokenization.html#indicberttokenizer.pad_token_id',
                                                                                                                'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.save_tokenizer': ( 'data_tokenization.html#indicberttokenizer.save_tokenizer',
                                                                                                                  'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.special_tokens': ( 'data_tokenization.html#indicberttokenizer.special_tokens',
                                                                                                                  'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.tokenize': ( 'data_tokenization.html#indicberttokenizer.tokenize',
                                                                                                            'indic_clip/data/tokenization.py'),
                                              'indic_clip.data.tokenization.IndicBERTTokenizer.vocab_size': ( 'data_tokenization.html#indicberttokenizer.vocab_size',
                                                                                                              'indic_clip/data/tokenization.py')}}}
